[package]
name = "fluvio-hub-util"
version = "0.0.0"
edition = "2021"
license = "Apache-2.0"
description = "API for SmartModule Hub"
authors = ["fluvio.io"]
repository = "https://github.com/infinyon/fluvio"
publish = false

[dependencies]
cargo_toml = { workspace = true }
const_format = "0.2"
dirs = { workspace = true}
ed25519-dalek = { version = "1.0.1", features = ["serde"] }
flate2 = "1.0"
hex = "0.4"
pem = "1.1"
rand = "0.8"
rand_core = "0.6"
sha2 = "0.10.6"
serde = { version="1.0", features=["derive"] }
serde_json = "1.0"
serde_yaml = "0.8"
ssh-key = { version="0.4.3", features=[ "ed25519" ] }
tar = "0.4"
pathdiff = { version = "0.2.1", default-features = false }
tempfile = { workspace = true }
toml = { workspace = true }
tracing = { workspace = true }
thiserror = { workspace = true }
wasmparser = { workspace = true }
reqwest = { workspace = true }
# added to make sure reqwest works
async-std = { version = "1.6.4", default-features = false, features = ["tokio1"] }

fluvio-future = { workspace = true }
fluvio-hub-protocol = { path = "../fluvio-hub-protocol" }
fluvio-types = { path = "../fluvio-types" }

[dev-dependencies]
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
